remove workflow

diff --git a/.github/workflows/lint-actions.yml b/.github/workflows/lint-actions.yml
--- a/.github/workflows/lint-actions.yml
+++ b/.github/workflows/lint-actions.yml
@@ -82,9 +82,23 @@ jobs:
           node-version: "${{ matrix.node-version }}"
 
       - name: "Check workflow files"
+        id: "actionlint"
         uses: "raven-actions/actionlint@v2"
         with:
           matcher: true
           cache: true
           fail-on-error: false
           flags: "-ignore SC2086"
+          github-token: "${{ secrets.GITHUB_TOKEN }}"
+
+      - name: "Summary"
+        if: ${{ steps.actionlint.outputs.exit-code != 0 }}  # example usage, do echo only when actionlint action failed
+        run: |
+          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
+          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
+          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
+          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
+          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
+          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
+          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"
+          exit ${{ steps.actionlint.outputs.exit-code }}
